import type { Metadata } from "next";
import "./globals.css";
import _App from "./_App";


export const metadata: Metadata = {
  title: "EraDigiLight",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link
        rel="icon"
        href="favicons/icon-white.png"
        type="image/<generated>"
        sizes="<generated>"
      />
      </head>
      <body>
        <_App>
          {children}
        </_App>
      </body>
    </html>
  );
}
